/** Allowed note icon ids — keep in sync with lib/noteIcons.ts NOTE_ICON_IDS. */

const NOTE_ICON_IDS = [
  'note',
  'file',
  'book',
  'bookmark',
  'document',
  'folder',
  'inbox',
  'archive',
  'clipboard',
  'list',
  'check',
  'task',
  'flag',
  'pin',
  'star',
  'heart',
  'bolt',
  'fire',
  'lightbulb',
  'brain',
  'target',
  'compass',
  'map',
  'globe',
  'link',
  'code',
  'terminal',
  'bug',
  'gear',
  'wrench',
  'database',
  'server',
  'cloud',
  'lock',
  'key',
  'shield',
  'user',
  'users',
  'mail',
  'chat',
  'phone',
  'calendar',
  'clock',
  'hourglass',
  'chart',
  'trending',
  'wallet',
  'tag',
  'search',
  'eye',
  'camera',
  'image',
  'music',
  'video',
  'mic',
  'rocket',
  'plane',
  'car',
  'home',
  'building',
  'briefcase',
  'gift',
  'trophy',
  'medal',
  'warning',
  'info',
  'question',
  'leaf',
  'sun',
  'moon',
  'sparkles',
] as const;

const ICON_SET = new Set<string>(NOTE_ICON_IDS);

/** Returns a valid icon id, or null for default / clear. */
export function normalizeNoteIcon(value: unknown): string | null {
  const s = String(value || '').trim();
  if (!s) return null;
  return ICON_SET.has(s) ? s : null;
}
